// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaqnelwtlxyhpbgbfajp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhcW5lbHd0bHh5aHBiZ2JmYWpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzAyMTYsImV4cCI6MjA3MzAwNjIxNn0.unae4WSXojEjdhggZRByEgRSDOkLaJsxA2cH14FUee0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});